name: Terraform Deployment

on:
  pull_request:
    branches: [ main ]
    types:
      - closed  # Triggers when a PR is closed

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.8
      

      # Step 3: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      # Step 4: Change directory
      - name: Change Directory
        run: cd terraform
      

      # Step 5: Terraform init
      - name: Initialize Terraform
        run: terraform init"
        working-directory: ./terraform

      # Step 6: Terraform plan
      - name: Terraform Plan
        run: terraform plan
        working-directory: ./terraform

      # Step 7: Terraform apply
      - name: Terraform Apply
        run: terraform apply --auto-approve
        working-directory: ./terraform
